version: '3.3'
services:
  api:
    container_name: meteoreo-api
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - './:/app:delegated'
    depends_on:
      - mariadb
    environment:
      - WEB_CONCURRENCY=2
      - PORT=80
      - PRE_START_PATH=/app/app/prestart.sh
      - GUNICORN_CMD_ARGS="--reload"
    ports:
      - '81:80'
    networks:
      - meteoreo-backend
    restart: always

  # daemon:
  #   container_name: meteoreo-daemon
  #   image: python:3.7
  #   volumes:
  #     - './:/app:delegated'
  #   depends_on:
  #     - mariadb
  #   command:
  #     - /app/meteoreo --scan --frequency=${SCAN_FREQUENCY}
  #   networks:
  #     - meteoreo-backend
  #   restart: always

  mariadb:
    image: mariadb
    container_name: meteoreo-mariadb
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_USER: '${MYSQL_USER}'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - 'meteoreodb:/var/lib/mysql'
    ports:
      - '3306:3306'
    networks:
      - meteoreo-backend
    restart: always

networks:
  meteoreo-backend:
    driver: bridge

volumes:
  meteoreodb:
    driver: local
