version: '3.3'

services:
  postgresql:
    image: postgres
    container_name: meteoreo-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:5432"
    networks:
      - meteoreo-backend

  mysql:
    image: mysql
    container_name: meteoreo-mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    networks:
      - meteoreo-backend

  api:
    container_name: meteoreo-api
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - './:/app:delegated'
    depends_on:
      - mysql
    environment:
      - WEB_CONCURRENCY=2
      - PORT=80
      - PRE_START_PATH=/app/app/prestart.sh
      - GUNICORN_CMD_ARGS="--reload"
    ports:
      - "81:80"
    networks:
      - meteoreo-backend

networks:
  meteoreo-backend:
    driver: bridge
